# Generated by Django 2.2.26 on 2022-03-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BandBrowser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='band',
        ),
    ]
