# Generated by Django 2.2.26 on 2022-03-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BandBrowser', '0002_remove_post_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField()),
                ('instruments', models.TextField(null=True)),
                ('linkedAccounts', models.TextField(null=True)),
                ('bio', models.TextField(null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='profile_images')),
                ('numberOfBands', models.IntegerField(default=0)),
            ],
        ),
    ]
